# Generated by Django 2.2.3 on 2019-07-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField()),
                ('definition', models.TextField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.Set')),
            ],
        ),
    ]
